export const FETCH_PRODUCTLIST_LOADING="FETCH_PRODUCTLIST_LOADING";
export const FETCH_PRODUCTLIST_SUCCESS="FETCH_PRODUCTLIST_SUCCESS";
export const FETCH_PRODUCTLIST_FAIL="FETCH_PRODUCTLIST_FAIL";

export const FETCH_PRODUCTDETAIL_LOADING="FETCH_PRODUCTDETAIL_LOADING";
export const FETCH_PRODUCTDETAIL_SUCCESS="FETCH_PRODUCTDETAIL_SUCCESS";
export const FETCH_PRODUCTDETAIL_FAIL="FETCH_PRODUCTDETAIL_FAIL";

export const FETCH_PRODUCTREVIEWS_LOADING="FETCH_PRODUCTREVIEWS_LOADING";
export const FETCH_PRODUCTREVIEWS_SUCCESS="FETCH_PRODUCTREVIEWS_SUCCESS";
export const FETCH_PRODUCTREVIEWS_FAIL="FETCH_PRODUCTREVIEWS_FAIL";

export const FETCH_VENDORREVIEWS_LOADING="FETCH_VENDORREVIEWS_LOADING";
export const FETCH_VENDORREVIEWS_SUCCESS="FETCH_VENDORREVIEWS_SUCCESS";
export const FETCH_VENDORREVIEWS_FAIL="FETCH_VENDORREVIEWS_FAIL";

export const UPDATE_PRODUCTDETAIL_LOADING="UPDATE_PRODUCTDETAIL_LOADING";
export const UPDATE_PRODUCTDETAIL_SUCCESS="UPDATE_PRODUCTDETAIL_SUCCESS";
export const UPDATE_PRODUCTDETAIL_FAIL="UPDATE_PRODUCTDETAIL_FAIL";

export const UPDATE_VENDORREVIEWS_LOADING="UPDATE_VENDORREVIEWS_LOADING";
export const UPDATE_VENDORREVIEWS_SUCCESS="UPDATE_VENDORREVIEWS_SUCCESS";
export const UPDATE_VENDORREVIEWS_FAIL="UPDATE_VENDORREVIEWS_FAIL";

export const UPDATE_PRODUCTREVIEWS_LOADING="UPDATE_PRODUCTREVIEWS_LOADING";
export const UPDATE_PRODUCTREVIEWS_SUCCESS="UPDATE_PRODUCTREVIEWS_SUCCESS";
export const UPDATE_PRODUCTREVIEWS_FAIL="UPDATE_PRODUCTREVIEWS_FAIL";

export const INPUT_SEARCH="INPUT_SEARCH";
export const INPUT_ADDRESS="INPUT_ADDRESS";
export const SET_FILTER="SET_FILTER";
export const SET_PREFERENCES="SET_PREFERENCES";

export const SET_AUTH_REQUEST="SET_AUTH_REQUEST";
export const SET_AUTH_SUCCESS="SET_AUTH_SUCCESS";
export const SET_AUTH_FAIL="SET_AUTH_FAIL";
export const SET_AUTH_LOTOUT="SET_AUTH_LOTOUT";

export const SET_OAUTH_REQUEST="SET_OAUTH_REQUEST";
export const SET_OAUTH_SUCCESS="SET_OAUTH_SUCCESS";
export const SET_OAUTH_FAIL="SET_OAUTH_FAIL";
export const SET_OAUTH_LOTOUT="SET_OAUTH_LOTOUT";

export const SET_USER_REQUEST="SET_USER_REQUEST";
export const SET_USER_SUCCESS="SET_USER_SUCCESS";
export const SET_USER_FAIL="SET_USER_FAIL";

export const UPDATE_USER_REQUEST="UPDATE_USER_REQUEST";
export const UPDATE_USER_SUCCESS="UPDATE_USER_SUCCESS";
export const UPDATE_USER_FAIL="UPDATE_USER_FAIL";

export const ADD_TO_CART="ADD_TO_CART";
export const REMOVE_FROM_CART="REMOVE_FROM_CART";
export const ITEM_QUANTITY_UPDATE="ITEM_QUANTITY_UPDATE";
export const CLEAR_CART="CLEAR_CART";

