export const FETCH_PRODUCTLIST_LOADING="FETCH_PRODUCTLIST_LOADING";
export const FETCH_PRODUCTLIST_SUCCESS="FETCH_PRODUCTLIST_SUCCESS";
export const FETCH_PRODUCTLIST_FAIL="FETCH_PRODUCTLIST_FAIL";

export const INPUT_SEARCH="INPUT_SEARCH";
export const INPUT_ADDRESS="INPUT_ADDRESS";

export const SET_AUTH_REQUEST="SET_AUTH_REQUEST";
export const SET_AUTH_SUCCESS="SET_AUTH_SUCCESS";
export const SET_AUTH_FAIL="SET_AUTH_SUCCESS";
export const SET_AUTH_LOTOUT="SET_AUTH_LOTOUT";

export const SET_USER_REQUEST="SET_USER_REQUEST";
export const SET_USER_SUCCESS="SET_USER_SUCCESS";
export const SET_USER_FAIL="SET_USER_FAIL";




